### ISSUE TITLE
game ctd in spectator script

### ISSUE THREAD

**Issue by Boberro** [ferstaberinde/F3#661] opened 2015-06-30 21:35 UTC
So I was spectating AI helicopter from first person view, when Zeus deleted that unit. Game crashed violently with some kind of "-12339578234953" out of memory error.

**Comment by cptnnick** [comment] 2015-06-30 21:39
Could you try uploading your .rpt file to pastebin and link it here?

**Comment by Boberro** [comment] 2015-06-30 22:44
http://pastebin.com/raw.php?i=qszueZ5t

**Comment by cptnnick** [comment] 2015-07-02 06:25
This is the information currently available on that exit code:

https://community.bistudio.com/wiki/Arma_3_Unusual_process_exit#0xC0000005_-_ACCESS_VIOLATION

Try following those instructions.

It's not an error explicitly caused by one of the scripts.

**Comment by Wolfenswan** [comment] 2015-08-24 22:47
Closing this as it's not caused by F3.

**Closed by Wolfenswan** 2015-08-24 22:47 UTC
