### ISSUE TITLE
Spectator Script + TFAR Functionality.

### ISSUE THREAD

**Issue by Khaosmatic** [ferstaberinde/F3#576] opened 2015-02-02 22:25 UTC
An issue we have been having a while which makes spectator chat useless is the effect when talking underwater is applied in the spectator lobby. Everyone is muffled and I cannot recall if you can hear alive units clearly either.

I used the basic TFAR Spectating layout but I cannot figure out the issue, it looks fine to me?

**Comment by cptnnick** [comment] 2015-02-02 22:30
The issue is the created virtual unit falls into the sea : D

It's fixed for the next version. In the meantime:

In f\aspect\fnCamInit.sqf, change it to look like this:
````
createCenter sideLogic;
_newGrp = createGroup sideLogic;
_newUnit = _createUnit ["VirtualCurator_F",[0,0,0],[],0,"FORM"];
_newUnit allowDamage false;
_newUnit hideObject true;
_newUnit enableSimulation false;
_newUnit setPos [0,0,5];
````

**Comment by Khaosmatic** [comment] 2015-02-02 23:39
Aha, so does is doing that as I thought! Ok thanks I will give this a try.

**Comment by Khaosmatic** [comment] 2015-02-02 23:46
Hmm, I don't have an 'aspect' folder?

**Comment by cptnnick** [comment] 2015-02-03 00:06
Typo! 'spect' obviously. Auto correct strikes again.

**Comment by Wolfenswan** [comment] 2015-02-03 11:30
Closing because issue is revolved and fixed in dev.

**Closed by Wolfenswan** 2015-02-03 11:30 UTC
